### ISSUE TITLE
Question: Dataset Example 

### ISSUE THREAD

**Issue by gamefundas** [landawn/AbacusUtil#1]
Hi, i have been trying to use the library for the past few days but I have been having a hard time due to limited documentation on the API usage. For example my primary purpose is to use Dataset through JdbcUtil and then apply, join/filter/merge etc on the resulting Dataset.

I guess reading from the DB and populating the Dataset was quick and easy. I was even able to join to Datasets but now I have to 

1. Calculate difference between two columns and store the value in a new column
2. Convert the output to a Map with the join key and value as the computed column

I couldnt even figure out how to iterate the Dataset and pull the values from specific columns and populate my pojo list.

Please let me know if there are examples to follow through and understand the usage semantics of the API.

**Comment by landawn** [comment]
There is no one-step API to do that in DataSet. but it's doable by stream API.

`
        Map<Object, Object> map = dataSet.stream(N.asList("columnName1", "columnName2")).toMap(
                a -> a[0].toString() + a[1].toString() /* Join Key: free to change to whatever you want*/,
                a -> a[0].hashCode() - a[1].hashCode() /* computed value: free to change to whatever you want*/ );
`
Suggestion: don't forget the  stream API it's extreme powerful if you stuck on the DataSet API

**Comment by landawn** [comment]
`
        Map<Object, Object> map = dataSet.stream(N.asList("columnName1", "columnName2")).toMap(
                a -> a[0].toString() + a[1].toString() /* Join Key: free to change to whatever you want*/,
                a -> a[0].hashCode() - a[1].hashCode() /* computed value: free to change to whatever you want*/ );`

**Comment by landawn** [comment]
DataSet implements Iterable interface, it's can be iterated by call iterator. or you can iterate it by converting it to List/xxx first. or iterate it by stream API. it depends the use case. i understood it may not be easy to use the API efficiently at the begin because there are so many methods. if you could go over each API in the dataset and stream API first and have whole the picture understanding. probably it will be more easy how to compose those APIs in your program.

**Comment by landawn** [comment]
There is no one-step API to do that in DataSet. but it's doable by stream API.

Map<String, Integer> map = dataSet.stream(N.asList(columnName1, columnName2)).toMap( a -> a[0].toString() + a[1].toString() /* Join Key: free to change to whatever you want*/, a -> a[0].hashCode() - a[1].hashCode() /* computed value: free to change to whatever you want*/ );

Don't forget the stream API. It's extreme powerful if you stuck on the DataSet API

**Comment by gamefundas** [comment]
@landawn thanks for sharing this. It was helpful. I guess the library is very useful overall. Could help with some examples of usage. The no. of utility methods and options can be overwhelming but documentation can make this library very useful.

**Comment by landawn** [comment]
we will add more documentations. At present, the temporary solutions are:
1 ,test it out, most of methods are very easy to test.
2, look into the source code. most of the codes are pretty simple
