### ISSUE TITLE
Dataset - Column names should be case insensitive

### ISSUE THREAD

**Issue by gamefundas** [landawn/AbacusUtil#10]
In my usage of dataset with some federated data sources (Oracle and Postgres) the column names could appear in capitals or lowercase depending on the source DB and its configuration. This becomes a problem when these datasets are joined with each other using their respective column names. For instance "id" fails to join with "ID". 

I believe Dataset columns names should be case insensitive so that mismatch doesn't occur during joins or referencing the columns with names.

**Comment by landawn** [comment]
I understand the situation. but here we keep the general rule in Java: `case sensitive`. you can either use alias in SQL:
```sql
select ID as 'id"....  // not sure if it works or not, i didn't test it with various db
```
Or rename the column before join
```java
ds.renameColumn("ID", "id");
```
Things will become much more complicated if column name is "case insensitive" in DataSet.

**Comment by gamefundas** [comment]
Closing this one as I was able to overcome this simply by column aliases or manipulating column names to my needs.
