### ISSUE TITLE
DataSet - serialize/deserialize

### ISSUE THREAD

**Issue by gamefundas** [landawn/AbacusUtil#11]
I found that there are very simple ways to serialize DataSet to csv/json/xml etc. But is there anything that can form a DataSet back again once its sent across the wire. I am looking to transport DataSet directly between components to avoid DTO's entirely.

N.newDataSet or any of the N.from don't seem to support this. I am thinking this must be there somewhere and I am not looking at the right place.

**Comment by landawn** [comment]
```java
static final JSONParser jsonParser = ParserFactory.createJSONParser();
......
String json = jsonParser.serialize(ds);
DataSet ds2 = jsonParser.deserialize(DataSet.class, json);
```
To convert CSV String/File to DataSet, please refer to `CSVUtil`.

By the way, `N.fromJSON/toJSON` does support the conversion between `DataSet` and `JSON` String.
```java
assertEquals(ds, N.fromJSON(DataSet.class, N.toJSON(ds)));
```

There is no API to support `xml -> DataSet`, it's not supported by N.fromXML/toXML too. the main purpose for DataSet.toXML is the generate the xml format text for display, not for transferring or storing.
