### ISSUE TITLE
Empty dataset with column headers

### ISSUE THREAD

**Issue by gamefundas** [landawn/AbacusUtil#12]
Was looking to create a dataset with empty rows in them but with column headers so that I can render the grid with an empty dataset. The following results in an exception.

DataSet ds1 = N.newDataSet(N.asList("id", "type", "amount"), null); // NullPointerException

DataSet ds1 = N.newEmptyDataSet(); //Doesn't have the column headers.

Any other way to do this?

Thanks
Andy

**Comment by gamefundas** [comment]
I guess the following will work.
DataSet ds1 = N.newDataSet(N.asList("id", "type", "amount"), N.emptyList());

**Comment by gamefundas** [comment]
It worked for me. Opened this issue a little too early. 
Think I am getting the hang of this amazing library. :)

Thx
Andy

**Comment by landawn** [comment]
Will add a new method in `N`: `DataSet newEmptyDataSet(final Collection<String> columnNames)`
