### ISSUE TITLE
Can we have better commit messages ?

### ISSUE THREAD

**Issue by goxr3plus** [landawn/AbacusUtil#13]
I would like to be a contributor on this project , found it today and seems very promising and amazing .

Looking on the commit messages to see what happens there is everywhere just release numbers instead of explaining words . This doesn't help future contributors :(

**Comment by landawn** [comment]
First of all, glad to hear that you're interested in this project and willing to make future contributions.
The answer to your request is: Absolutely, I will add more detailed commit messages.

Currently, I'm still focus on stabilizing the APIs. It may take couple of months. I will let the people know when it's ready for accepting change requests. Before that, please focus on the user experiences provided by the APIs provided in Abacus-Util. if you have any suggestions or change requests, please let me know. thanks.
