### ISSUE TITLE
Sql Server is not working with JdbcUtil

### ISSUE THREAD

**Issue by SaSa1983** [landawn/AbacusUtil#16]
This is because of a typo in JdbcUtil.
I created a pull request fixing this problem: https://github.com/landawn/AbacusUtil/pull/15

**Comment by landawn** [comment]
Thank you!
It will be checked in and included in this weekend's release 1.5.7

**Comment by landawn** [comment]
@SaSa1983 I will close this issue if there is no further question.

**Comment by SaSa1983** [comment]
I'm okay with closing the issue

landawn <notifications@github.com> schrieb am Do., 21. März 2019, 05:39:
