### ISSUE TITLE
IN clause value in SQLExecutor

### ISSUE THREAD

**Issue by infinite-sahil** [landawn/AbacusUtil#17]
I was trying to figure out, how we can pass in parameter value.
Suppose: i have a query: 

"SELECT ID FROM EMPLOYEES WHERE DEP_ID IN ( ? ) and NAME LIKE '%?%' "

DEP_IN :- 1,2,3,4,5,6 and NAME value :- somebody
How can we use SQLExcecutor to run this query?

**Comment by landawn** [comment]
I think the SQL should be:
```
String sql = "SELECT ID FROM EMPLOYEES WHERE DEP_ID IN ( ?, ?, ?, ?, ?, ? ) and NAME LIKE '%?%' ";
```
And
```
sqlExecutor.query(..., sql, N.asList(1, 2, 3, 4, 5 ,6, "somebody"));
```

Or you can prepare your query by SQLBuilder:
```
p = NE3.select("ID").from("EMPLOYEES").where(L.in("ID", ids).and(L.like("NAME ")).pair();
sqlExecutor.query(..., p.sql, p.parameters);
````
you could have a try.
I don't have time to test the above code right now. if anything is wrong, i will correct it later

**Comment by infinite-sahil** [comment]
Thank you for your earlier response,

by the time, i somehow managed to achieve it.
by replacing replaceMe in the below query with the size of the dept_id list i want to pass.

bit similar to the one you shared above.

"SELECT ID FROM EMPLOYEES WHERE DEP_ID IN ( replaceMe ) and NAME LIKE '%?%'"

This API is really amazing, kindly add some good documentation with examples,
by this more developer gonna start using this API.

**Comment by landawn** [comment]
@infinite-sahil Thanks! I have almost finished the major coding part. It will soon be opened anybody who would like to contribute the Doc part.
