### ISSUE TITLE
Question: JSON to DataSet conversion

### ISSUE THREAD

**Issue by infinite-sahil** [landawn/AbacusUtil#20]
Hi,

I am looking out for something that can create a DataSet from a json String.
**For example:**
```
DataSet ds =
                N.newDataSet(
                        N.asLinkedHashMap("ID", N.asList(1, 2),
                                "NAME", N.asList("SAHIL", "NITESH"),
                                "DATA", N.asList("{\"age\": \"27\", \"FATHER_NAME\": \"DHRAM\"}", "{\"age\": \"26\", \"fatherName\": \"PARAM\"}")));
```

As shown above, my DATA column contains json and now i want to convert this json to a new DataSet.
is there any quick way in API using which i can achieve this.

Actually I am looking for solution urgently, can you please help

**Comment by landawn** [comment]
Try
```
ds.updateColumn("DATA", (String val) -> N.fromJSON(yourTargetType, val)); // target type could be map or entity with getter/setter methods.
```

**Comment by infinite-sahil** [comment]
Hi @landawn 

can you please elaborate a bit more, i am getting this error
Exception in thread "main" Error on parsing at ending '"' with 27

**Sharing below my sample code:**
can you please assist on this.
public class Test {

    public static void main(String[] args) {
        DataSet ds =
                N.newDataSet(
                        N.asLinkedHashMap("ID", N.asList(1, 2),
                                "NAME", N.asList("SAHIL", "NITESH"),
                                "DATA", N.asList("{\"age\": 27, \"TRADE_NO\": \"DHRAM\"}", "{\"age\": 26, \"fatherName\": \"PARAM\"}")));

        ds.println();
        int dataIdx = ds.getColumnIndex("DATA");

        ds.updateColumn("DATA", (String val) -> N.fromJSON(DataSet.class, val));
    }
}

class Person {

    public int age;
    private String tradeNo;

    public int getAge() {
        return age;
    }

    public void setAge(final int age) {
        this.age = age;
    }

    public String getTradeNo() {
        return tradeNo;
    }

    public void setTradeNo(final String tradeNo) {
        this.tradeNo = tradeNo;
    }

}

**Comment by landawn** [comment]
Try: `ds.updateColumn("DATA", (String json) -> N.fromJSON(Person.class, sjon))`. I think the target column type is `Person.class`, not `DataSet.class`. you can also try [lombok](https://projectlombok.org/) for you test bean class:
```
@Data
static class Person {
    private String tradeNo;
    private String fatherName;
    private int age;
}
```
By the way,  A small tip to find/lookup APIs/methods in abacus-util: 
`IOUtil` -> IO related operations.
`StringUtil` -> String related operations.
...
There are also hundreds of (probably more than one thousand) most daily used APIs defined in `N`. if you're using eclipse or other IDE, you try to search operations by typing `N.keywords`, for example: `N.json`, all json related operations will popup; `N.sort` all sort related operations will popup.

**Comment by infinite-sahil** [comment]
Thank you @landawn for your quick response. 
Closing this question.
