### ISSUE TITLE
IndexOutOfBoundsException comes in case of empty dataset

### ISSUE THREAD

**Issue by infinite-sahil** [landawn/AbacusUtil#21]
Hi @landawn,

I am getting **IndexOutOfBoundsException** whenever i perform following actions:
   1. Joining 2 dataSets out of which 1 dataSet is empty.
         **Example:**
      ```
        final DataSet dataSet1 = N.newDataSet(N.asLinkedHashMap(
                "ACCT_ID", N.asList("1", "2"),
                "ACCT_NM", N.asList(11, 12)));

        final DataSet dataSet2= N.newEmptyDataSet(N.asList("ACCT_ID_1","ACCT_NM_1"));

        DataSet joinedDataSet = dataSet1.innerJoin(dataSet2, N.asMap("ACCT_ID", "ACCT_ID_1"));

```
   2. updating column in case of empty dataSet: 
          **Example:**
       
         final DataSet idDataSet = N.newEmptyDataSet(N.asList("ID"));
         idDataSet.updateColumn("ID", (Try.Function<String, Object, RuntimeException>) Long::valueOf);
```

I believe this empty check should be part of the API, otherwise as a consumer everybody have to write this check before using above functions.

**Comment by landawn** [comment]
I agree that all the methods in `DataSet` should be compatible and work fine with empty DataSet.
The root cause for above issue mostly is in `N.newEmptyDataSet(columnNames)`, not in `DataSet`
The implementation for `newEmptyDataSet` looks like:
```
new RowDataSet(new ArrayList<>(columnNames), new ArrayList<List<Object>>());
```
This is wrong. it should be:
```
final List<List<Object>> columnList = new ArrayList<>(columnNames.size());

for (int i = 0, size = columnNames.size(); i < size; i++) {
    columnList.add(new ArrayList<>(0));
}

return new RowDataSet(new ArrayList<String>(columnNames), columnList);
```
I will fix this issue in next release and add validation in DataSet to make sure sizes of column name list and column list are same.

I tested the `join` with empty `DataSet` not created by `N.newEmptyDataSet`. it works fine.
```
final DataSet dataSet1 = N.newDataSet(N.asLinkedHashMap("ACCT_ID", N.asList("1", "2"), "ACCT_NM", N.asList(11, 12)));

final DataSet dataSet2 = N.newDataSet(N.asList("ACCT_ID_1", "ACCT_NM_1"), N.asList(N.asList("id1", "nm1")));
dataSet2.println();

dataSet2.clear();

dataSet2.println();

dataSet2.updateColumn("ACCT_ID_1", Fn.<String, Long> f(Long::valueOf));

dataSet1.innerJoin(dataSet2, N.asMap("ACCT_ID", "ACCT_ID_1")).println();
dataSet1.fullJoin(dataSet2, N.asMap("ACCT_ID", "ACCT_ID_1")).println();
```
please let me know if you have different use case/test scenarios for this issue.

**Comment by infinite-sahil** [comment]
Yah, you are right, this issue is occurring in case of  creating dataSet using N.newEmptyDataSet.
else things works fine. will wait for the new release :) 

Happy coding 👍 

can you please brief list of few useful classes/interfaces in abacus -> like i saw you used **Fn** that too has some good functions.

**Comment by infinite-sahil** [comment]
@landawn  when I can get version 1.7.8 on maven ?

**Comment by landawn** [comment]
@infinite-sahil It's available now.

And as you may or will know, There are couple of alternatives for `(Try.Function<String, Object, RuntimeException>) Long::valueOf`, :

-  cast by com.landawn.abacus.util.function.Function: `(Function<String, Object>) Long::valueOf`

-  use: `(String val) -> Long.valueOf(val)`

- `Fn.<String, Long> f(Long::valueOf)`

- use or add new utility method. for example: `Fn.parseLong()`, which just added in 1.7.8 release.

**Comment by landawn** [comment]
By the way, if you're interested in Functional Programming, you could have a look at the section `Functional Programming` in this project main page

**Comment by infinite-sahil** [comment]
Thank you @landawn .
I verified it and its working perfectly fine.
