### ISSUE TITLE
SQLExecutor: with in clause accepting list of values

### ISSUE THREAD

**Issue by infinite-sahil** [landawn/AbacusUtil#24]
Hi @landawn 

I need your urgent help with below issue.
I am using SQLExecutor, my query looks like this:
 
`"SELECT ID FROM EMPLOYEES WHERE DEP_ID IN (replacMe)"`

Now suppose, i want to fetch ids of all employees whose dep_id is 1, 2 or 3.
so i replace string **replaceMe** with the 3 (?, ?, ?) in the query and query becomes like.

`"SELECT ID FROM EMPLOYEES WHERE DEP_ID IN (?, ?, ?)"`

When i execute this query it throws error: 
SQLException|17041|Missing IN or OUT parameter at index:: 1

can you please help me in this.

**Comment by landawn** [comment]
Did you pass the parameters and how if yes?

**Comment by infinite-sahil** [comment]
Thank you for the early response.

considering above example, now my query has 3 (?) instead of 1.
and i take func ( Object... parameters) as an input , which contains the value of these bind variables.

**Comment by infinite-sahil** [comment]
pseudo code of my function looks like this:

public void insertInDatabase(String sql, Object... paramValues){
// 1.  replace - replaceMe phrase from the sql String with the ? ( N times,  n is the size of paramValues )
// 2. execute the query using SQLExecutor: executor.query(sql, paramValues);          
}

**Comment by landawn** [comment]
`parameters` can be `Object[]/List` or `Map/Entity` for named parameter query. for example:
```
insertInDatabase(sql, 1, 2, 3);
// OR
insertInDatabase(sql, N.asList(1, 2, 3));
```
if what you pass is `int[]`, it won't work. for example:
```
int[] ids = {1, 2, 3};
insertInDatabase(sql, ids); // won't work
```

**Comment by infinite-sahil** [comment]
one more thing apart from above mentioned,
how can i see, what sql is passed to database from SQLExecutor finally.
so i can easily check whats going wrong.

**Comment by infinite-sahil** [comment]
but i am passing input as Set<String>ids and caching it in Object in the insertInDatabase function so that this can work with any datatype.

What do you suggest, how can i make above one running.

**Comment by landawn** [comment]
Using `JdbcSetting.setLogSQLWithParameters(true)`,  log4j2/logback/slf are supported. you can log the sql to your log file or print it out to console.

**Comment by infinite-sahil** [comment]
I turned on this parameter and my sql is getting printed:

SELECT ID FROM EMPLOYEES WHERE DEP_ID IN (?, ?, ?) {[1, 2, 3]}

**Comment by landawn** [comment]
probably what you passed is an  `int[]`. Here is my sample:
```
    @Test
    public void issue_24() {
        String sql = "SELECT * FROM user WHERE ID IN (replacMe)";
        insertInDatabase(sql, 1, 2, 3);
        insertInDatabase(sql, N.asList(1, 2, 3));
        insertInDatabase(sql, N.asSet(1, 2, 3));
    }

    public void insertInDatabase(String sql, Object... paramValues) {
        String newSql = sql.replace("replacMe", SQLBuilder.repeatQM(paramValues.length));
        sqlExecutor.execute(newSql, paramValues);
    }

    public void insertInDatabase(String sql, Collection<?> paramValues) {
        List<Object> params = paramValues instanceof List ? (List) paramValues : N.newArrayList(paramValues);
        String newSql = sql.replace("replacMe", SQLBuilder.repeatQM(paramValues.size()));
        sqlExecutor.execute(newSql, params);
    }
```

**Comment by infinite-sahil** [comment]
Let me show my sample code:

 ```
public long insert(final String queryDataName, final Object... parameters) {
        log.info("Inserting data for {} with parameters {}", queryDataName, Arrays.toString(parameters));
        final Query q = fetchQuery(queryDataName);
        if (q.getSourceName().startsWith(DatabaseType.XYZ.name()))
            return xyzSQLExecutor.insert(q.getSql(), parameters);
        else
            return abcSQLExecutor.insert(q.getSql(), parameters);
    }
```


calling method:
placeHolderValues --> this is a list
dsRepository.query(QueryName.SQL_DUMMY, preparePlaceHolders(curIds.size()), placeHolderValues);
          


 private static String preparePlaceHolders(int length) {
        return String.join(", ", Collections.nCopies(length, QUESTION_MARK));
    }

**Comment by landawn** [comment]
are you doing `insert` or `query`? please help to print out below log before:  `xxxorabcSQLExecutor.insert(q.getSql(), parameters)`
```
log.info("sql: " + sql + ", parameters: " + parameters.getClass() + ", parameters[0]: " + parameters[0].getClass() + ", values: " + N.toString(parameters));
```

**Comment by infinite-sahil** [comment]
mybad, i am querying, as i can't disclose confidential code, so i typed manualy here.

**Comment by infinite-sahil** [comment]
@landawn 
Thanks a lot, it worked finally,
Thanx a ton mahn for your help.

you are champ :)
