### ISSUE TITLE
Batch inserts are extremely slow

### ISSUE THREAD

**Issue by gamefundas** [landawn/AbacusUtil#25]
Our SQLExecutor batch inserts are taking a very long time. In the example below for a batch size of 5000 and inserting 19764 rows, it took more than 5 min.

dbSQLExecutor.batchInsert(q.getSql(), SQLExecutor.JdbcSettings.create().setBatchSize(5000)
                    , dataToBeInserted);

Is there any way to optimize this? We are using default JDBCSettings at this point. Not sure if it supports anything that will help in improving the performance.

**Comment by landawn** [comment]
Generally, I need some very basic info: what's table schema and indexes created? how many records does the table have before executing the batch insert? but before we go to there. you can do a two tests to verify the issue by yourself: 
1, insert 1000 records one by one, without batch.
2, insert 1000 records by batchInsert, set batch size to 100 or 200.
if it's slow, you need to take a look at your table schema&design.

**Comment by landawn** [comment]
i did a test at [batch_25](https://github.com/landawn/abacus-util/blob/master/samples/com/landawn/abacus/samples/SQLExecutorTest.java), inserting 19764 records into a small table can be done in couple of seconds.

**Comment by landawn** [comment]
@gamefundas is the issue resolved?
I assume you're inserting those records into a table with ten of millions records and a few indexes, if that's true, based on my personal experiences, Here are the approaches i would like to recommend:

-  minimum hardware: 4 cores + 16 GB memory + SSD driver.

- Drop the unnecessary indexes.

I may close this issue in a week if there is no update.
