### ISSUE TITLE
Postgres SQL cast syntax confuses Abacus SQLExecutor

### ISSUE THREAD

**Issue by gamefundas** [landawn/AbacusUtil#26]
The following SQL is an example where we update the properties of json data with the following UPDATE statement

update my_table mt
          set data = data || '{"QUANTITY": ?, "AMOUNT": ?, "AMT_LOCL": ?}'
       where mt.data ->> 'TRAN_ID'::text = ? and
              mt.data ->> 'ACCT_ID'::text = ? and
              mt.process_id = ?

com.landawn.abacus.exception.AbacusException: can't mix '?' and '#{propName}' in the same sql script

To me it appears, "::text" is being confused with a named bind parameter.

**Comment by landawn** [comment]
will fix it in next release 1.8.10

**Comment by landawn** [comment]
@gamefundas please help to this with version 1.8.13
