### ISSUE TITLE
DynamoDBExecutor is missing

### ISSUE THREAD

**Issue by yilativs** [landawn/AbacusUtil#3]
DynamoDBExecutor is mentioned in http://www.landawn.com/DynamoDBExecutor_view.html but missing in code base.
Where this class can be found?

**Comment by landawn** [comment]
Are you talking about source code or jar file? if it's *.jar, `DynamoDBExecutor` are excluded from `abacus-android-*.jar` due to limit of method size on android. if it's source code, just uploaded it to GitHub, please check it out now.

**Comment by yilativs** [comment]
I'd like to see it in code, last code commit according to git hub was 13 hours ago, have you pushed the code?
If yes, to which branch?

**Comment by landawn** [comment]
it's on master: https://github.com/landawn/AbacusUtil/tree/master/src/com/landawn/abacus/util

**Comment by yilativs** [comment]
Thank you, now it popup.  I'm closing the issue.

PS I see you don't use LastEvaluatedKey (see http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html#Query.Pagination for details).
Perhaps it is another issue, cause if your dataset is > then 1MB you won't get the whole page.

**Comment by landawn** [comment]
Thank you for pointing it out. 0.9.82 has been released with the fix for this issue.
