### ISSUE TITLE
SQLExecutor - WITH clause or CTE support

### ISSUE THREAD

**Issue by gamefundas** [landawn/AbacusUtil#9]
I am having trouble executing queries containing WITH clause or CTE. After debugging I ended up at the following line in SQLExecutor that fails to find any parameters to bind. Tried named and positional parameters. Both resulted in the same.

final int parameterCount = namedSQL.getParameterCount();

Error in case of positional param:
No value specified for parameter 1.' and exception = 'No value specified for parameter 1.'

Error in case of named parameters
PSQLException: ERROR: syntax error at or near ":"

Other SQL's starting with "SELECT" seem to work fine.

My SQL looks something like below, an example structure as the original is much more complex

`
WITH context as (
     SELECT ? as days, ? as curcy FROM DUAL
),
transactions as (
     SELECT t.* from schema.transactions_tbl t, context c WHERE t.curcy_cd = c.curcy_cd and t.dt <= sysdate - c.days
)
SELECT * FROM transactions t WHERE t.status = ''SUCCESS'
`

I noticed that NamedSQL failed to parse and identify those two bind variables. Am I missing something or the code only works when the SQL starts with SELECT clause.

**Comment by gamefundas** [comment]
Ran few more tests.

SELECT ? as curcy FROM DUAL - works

WITH CTX AS (SELECT 'USD' as curcy FROM DUAL) SELECT * FROM CTX - works

WITH CTX AS (SELECT ? as curcy FROM DUAL) SELECT * FROM CTX - Fails to bind parameter

WITH CTX AS (SELECT 'USD' as curcy FROM DUAL) SELECT * FROM CTX WHERE CURCY = ? - Fails again

Its clear SQL's starting with WITH clause isnt supported. Cant see the NamedSQL.getParameterCount() code so hard to tell if its built on the assumption that SQL's will start with known keywords such as SELECT.

Any possibility this can be fixed soon as many of our SQL use the CTE feature.

**Comment by landawn** [comment]
Try latest version 1.2.10

**Comment by gamefundas** [comment]
Awesome. This fixes it.
